### ISSUE TITLE
Strings in input currently are not allowed to contain spaces

### ISSUE THREAD

**Issue by rainerschoe** [IBM/gWhisper#1]
**Describe the bug**
    $ ./gwhisper 127.0.0.1 helloworld.Greeter SayHello name=asd fsd
    Parse failed. Parsed until: '127.0.0.1 helloworld.Greeter SayHello name=asd'
also
    $ ./gwhisper 127.0.0.1 helloworld.Greeter SayHello name="asd fsd"
    Parse failed. Parsed until: '127.0.0.1 helloworld.Greeter SayHello name=asd'

**To Reproduce**
see above

**Expected behavior**
    $ ./gwhisper 127.0.0.1 helloworld.Greeter SayHello name="asd fsd"
    2019-03-06 16:08:55: Received message:
    | message = "Hello asd fsd"
    RPC succeeded :D

**Comment by Hendrik-H** [comment]
The same issue occurs when the argument value contains a colon (`:`).

**Comment by rainerschoe** [comment]
fixed in master, leaving issue still open, as function tests need to be implemented to ensure this via CI.

**Comment by Hendrik-H** [comment]
awesome, works for me now :-)

**Comment by rainerschoe** [comment]
closing, as it seems to work for users
