### ISSUE TITLE
Integrate and finish CMake rework

### ISSUE THREAD

**Issue by rainerschoe** [IBM/gWhisper#100]
Goal is to allow
- Retrieving and building gRPC, protobuf and gtest as dependencies automatically during build (user does not need to install external dependencies for gWhisper)
- Static linkage of gWhisper
- Allow cross-compiling of gWhisper

@FP-Guitar already started work on this and created a PR #99 which still needs some work however.

**Comment by FP-Guitar** [comment]
Will continue to do some work. Have already done some stuff locally.

**Comment by rainerschoe** [comment]
This was completed and successfully merged in #106 yayy :)
