### ISSUE TITLE
JSON output of responses

### ISSUE THREAD

**Issue by FP-Guitar** [IBM/gWhisper#111]
If we want to use gWhisper for test automation. An machine readable standard format would be great. JSON should be a good choice, because it is supported by almost every language so far.

I could imagine just adding a flag -output=JSON or something similar, and the tool writes then json to standard out.

Useful for: Everyone who runs gWhisper as test tool and wants to run it as part of its regression.

Maybe I start implementing myself. As protobuf supports json out of the box, it should not be that hard.

**Comment by FP-Guitar** [comment]
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util

**Comment by rainerschoe** [comment]
implemented in #120
