### ISSUE TITLE
Can not compile due to missing include

### ISSUE THREAD

**Issue by hermannolafs** [IBM/gWhisper#116]
**Describe the bug**
Following the build guide failed for me with this message:
```
gWhisper/src/libCli/MessageParsing.cpp:374:23: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char>'
    std::stringstream outstream;
```

**To Reproduce**
Follow build guide on `darwin_arm64`, with test server disabled.

**Expected behavior**
Build succeeds and executable binary is produced.

**Provide details about your environment**
 - Operating System version: MacOS 11.2.2 (20D80)
 - `gwhisper --version` output: 
 - gRPC/protobuf version: `v1.42.0`
 - Compiler version (if related to build): `Apple clang version 12.0.5 (clang-1205.0.22.11)`
 - CMake version (if related to build): `3.22.1`

**Additional context**

**Comment by hermannolafs** [comment]
Fixed in this PR

https://github.com/IBM/gWhisper/pull/115
```
 > gwhisper --version
Git identifier: v3.3.1-113-g22f0282 Build date: 2021-12-14_18:49:34 NoUncommitedChanges NoUntrackedFiles
```

**Comment by rainerschoe** [comment]
Thanks for reporting this and opening a PR :-)
It seems the arm64 compiler uses a different order of includes, which is why we did not detect this problem before.

I will integrate your PR as soon as possible. However we are currently in progress of migrating from TravisCI to Github-Actions and hence have some issues with CI, so don't worry if the PR reports failing CI run.

**Comment by hermannolafs** [comment]
Good to know, Thanks!

**Comment by hermannolafs** [comment]
Fixed with #115 !

**Comment by hermannolafs** [comment]
My fix was accidentally removed in #120 
https://github.com/IBM/gWhisper/pull/120/files#diff-dadbfd93a97ce88ce03e5d2344da0b2b279324a3011651bb2bc6059e4adc35baL18

**Comment by rainerschoe** [comment]
Hi @hermannolafs Oh yes sorry about this. Was lost in JSON implementation :) Should be fixed now in master branch. Thanks for reporting.

**Comment by hermannolafs** [comment]
Thank you!
