### ISSUE TITLE
latest build of abseil-cpp failed with `elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword`

### ISSUE THREAD

**Issue by ja66** [IBM/gWhisper#151]
**Build fail**
Build fail with `elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword` in 3rd party code in 
`build/_deps/grpc-src/third_party/abseil-cpp/absl/strings/internal/str_format/extension.h:34`

Reason is a missing include of `#include <cstdint>` before.
```C++
#include <cstdint>

#include "absl/base/config.h"
#include "absl/base/port.h"
#include "absl/meta/type_traits.h"
#include "absl/strings/internal/str_format/output.h"
#include "absl/strings/string_view.h"

namespace absl {
ABSL_NAMESPACE_BEGIN

enum class FormatConversionChar : uint8_t;
enum class FormatConversionCharSet : uint64_t;
```

I was able to complete the build (a few warnings though).
I wonder whether the include statement could be done outside of the fetched as a cmake statement.

**Comment by rainerschoe** [comment]
reproduced with `gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)`

**Comment by rainerschoe** [comment]
I added PR #152 to step up gRPC version, which should fix this issue.

@ja66 : would you be willing to review this PR? (I somehow cannot request an official review from you, probably because you are not in the correct ORG)
