### ISSUE TITLE
cppcheck is complaining about generated code

### ISSUE THREAD

**Issue by rainerschoe** [IBM/gWhisper#37]
**Describe the bug**
```
...
[/home/travis/build/IBM/gWhisper/build/tests/testServer/examples.pb.h:3245]: (style) Condition 'GetArenaNoVirtual()==NULL' is always true
[/home/travis/build/IBM/gWhisper/build/tests/testServer/examples.pb.h:3277]: (style) Condition 'message_arena==NULL' is always true
[/home/travis/build/IBM/gWhisper/build/tests/testServer/examples.pb.h:3299]: (style) Condition 'GetArenaNoVirtual()==NULL' is always true
...
```

**To Reproduce**
trigger a travis build

**Expected behavior**
Generated code not checked (at least not generated code from protoc or other third-party code generators).

**Comment by ericboehmler** [comment]
Suppressing all code inside the build/ directory. That's the output as of today:

$ cppcheck --enable=warning,style,performance,portability,unusedFunct...
[.../gWhisper/src/libArgParse/GrammarElement.hpp:129]: (style) Consid...
[.../gWhisper/src/libArgParse/Alternation.hpp:103]: (style) Consider ...
[.../gWhisper/src/libCli/MessageParsing.cpp:272]: (style) Consider us...
[.../gWhisper/tests/testServer/ServiceComplexTypeRpcs.cpp:84]: (style...
The command "cppcheck --enable=warning,style,performance,portability,...
