### ISSUE TITLE
exception on conversion

### ISSUE THREAD

**Issue by rainerschoe** [IBM/gWhisper#56]
./gwhisper 127.0.0.1 examples.NestedTypeRpcs echoNestedMaps simple_map_string=::key=8 value=ad::
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
Aborted (core dumped)

**Comment by taojunli** [comment]
If user input "key=8 value=0xad::", the as which could be intercepted as a hex number(0XAD), without "0x" the stoul() will throw the exception.

Hence here only the value starts with "0x|0X", likes "value=0xFF::" is allowed, or "value=FF::" is allowed as well? Is default number base decimal?

**Comment by rainerschoe** [comment]
only hex numbers starting with 0x or 0X are allowed
others should be interpreted as decimal.

core dump here is a bug.
We should either return a meaningful error message, or implement better regex in the grammar parser to only allow valid values to be parsed
