### ISSUE TITLE
fish shell autocompletion error

### ISSUE THREAD

**Issue by callalilychen** [IBM/gWhisper#64]
**Describe the bug**
I got the following error message with fish shell: 
```
⋊> ~/t/gWhisper on 3af9796 ⨯ gwhisper /usr/share/fish/vendor_completions.d/gwhisper.fish (line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $commandName'.
$commandName --complete=fish $args
^
in command substitution
	called on line 0 of file /usr/share/fish/vendor_completions.d/gwhisper.fish

in function “getCompletions”
	called on standard input

in command substitution
	called on standard input

gwhisper                     gwhisper                                                              17:17:04                     17:17:04
```
**To Reproduce**
in shell tip gwhisper and then tab

**Expected behavior**

**Provide details about your environment**
 - Operating System version:
 - `gwhisper --version` output:
```
fish, version 2.7.1
```
 - gRPC/protobuf version: no idea
 - Compiler version (if related to build):

 - CMake version (if related to build):
```
⋊> ~ cmake --version                                        17:20:49
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake)
```

**Additional context**
I use actually [oh my fish](https://github.com/oh-my-fish/oh-my-fish)

**Comment by callalilychen** [comment]
after destroy `omf`, I still get the error. So I think not because of `omf`.

**Comment by callalilychen** [comment]
ok, use fish 3.0.2 solve the problem

**Comment by rainerschoe** [comment]
should work now, could you verify?

**Comment by callalilychen** [comment]
Unfortunately no. because I have fish 3 now. but I tested in a docker with fish2. I can not reproduce the error.
