### ISSUE TITLE
make completion friendly interactive

### ISSUE THREAD

**Issue by callalilychen** [IBM/gWhisper#65]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I tab, only `:` is completed in fish shell
I'm always frustrated when I tab at end of a message,  `: : ` is completed in bash shell
I'm always frustrated when I tab nothing is completed because a number is expected
I'm always frustrated when I tab enter and the app does not terminate

**Describe the solution you'd like**
I'm always frustrated when I tab, only `:` is completed in fish shell
=> possible to complete space? or some hints
I'm always frustrated when I tab at end of a message,  `: : ` is completed in bash shell
=> only one `:` is compeletet
I'm always frustrated when I tab nothing is completed because a number is expected
=> I need some hints, that an integer is expected
I'm always frustrated when I tab enter and the app does not terminate
=> terminate gWhisper also after streaming

**Describe alternatives you've considered**
-

**Describe why you think this feature is useful for gWhisper users**
to be interactiver. improve user experence

**Additional context**
Maybe two many request to the server? My server always receive empty message after using gWhisper

**Comment by rainerschoe** [comment]
Thanks for reporting this.
Please describe how to reproduce the issues.
Provide example commandline invocations and the sequences of keys you are pressing.
Then describe what you see and what you expect to see/happen instead.

**Comment by callalilychen** [comment]
I got for example the following debug log after using gwhisper, which does not terminate:

```
INFO:werkzeug:127.0.0.1 - - [08/Aug/2019 14:28:04] "POST /app/1 HTTP/1.1" 200 -
DEBUG:root:Empty request quque for app 1
DEBUG:root:Empty request quque for app 1
DEBUG:root:Empty request quque for app 1
DEBUG:root:Empty request quque for app 1
```

**Comment by rainerschoe** [comment]
Hmmm...
Still not sure what your environment is and what RPC you are calling, but the log output gives information about queue status. In this case the request queue is empty, which might be a desired sate, depending on your application.

If you have a server-side streaming RPC (meaning the server is streaming messages to the caller) gWhisper will not terminate until the server finishes the stream (either by calling [Finish](https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_async_writer.html#a330082d0766d6867517a54919d650a20) for async servers or ending the RPC for sync servers).

**Comment by callalilychen** [comment]
@rainerschoe now I found out, why gwhisper does not terminate. and the log is actually from another application. Sorry for the confusion.

**Comment by rainerschoe** [comment]
closing as most of the problems discussed here were unrelated to gWhisper
