### ISSUE TITLE
Unable to build gWispher on ubuntu 19.10

### ISSUE THREAD

**Issue by ekarlso** [IBM/gWhisper#75]
cmake .
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- PROTOC = /usr/local/bin/protoc
-- PROTOC_GRPC_PLUGIN = /usr/local/bin/grpc_cpp_plugin
-- PROTO_FILE_BASE_SRC_PATH = /home/ekarlso/software/gWhisper/src/protoDoc
-- PROTO_FILE_BASE_DST_PATH = /home/ekarlso/software/gWhisper/src/protoDoc
CMake Warning at CMakeLists.txt:62 (message):
  googletest submodule not found, not building tests.  Please be sure to get
  the submodules with 'git submodule update --init' to also build tests.

-- PROTOC = /usr/local/bin/protoc
-- PROTOC_GRPC_PLUGIN = /usr/local/bin/grpc_cpp_plugin
-- DYNAMIC GRPC LINKING INFO = -Wl,--no-as-needed;/usr/local/lib/libgrpc++_reflection.so;-Wl,--as-needed;/usr/local/lib/libgrpc++.so;/usr/local/lib/libgrpc.so;/usr/local/lib/libprotobuf.so
-- PROTO_FILE_BASE_SRC_PATH = /home/ekarlso/software/gWhisper/third_party/gRPC_utils
-- PROTO_FILE_BASE_DST_PATH = /home/ekarlso/software/gWhisper/third_party/gRPC_utils
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ekarlso/software/gWhisper
ekarlso@ekarlso-p1:~/software/gWhisper$ make all
[  4%] Generating protoDoc.grpc.pb.cc, protoDoc.grpc.pb.h
[  9%] Generating protoDoc.pb.cc, protoDoc.pb.h
Scanning dependencies of target protoDoc
[ 13%] Building CXX object src/protoDoc/CMakeFiles/protoDoc.dir/protoDoc.pb.cc.o
[ 18%] Building CXX object src/protoDoc/CMakeFiles/protoDoc.dir/protoDoc.grpc.pb.cc.o
[ 22%] Linking CXX static library libprotoDoc.a
[ 22%] Built target protoDoc
Scanning dependencies of target ArgParse
[ 27%] Building CXX object src/libArgParse/CMakeFiles/ArgParse.dir/ArgParse.cpp.o
[ 31%] Linking CXX static library libArgParse.a
[ 31%] Built target ArgParse
[ 36%] Generating reflection.grpc.pb.cc, reflection.grpc.pb.hh
[ 40%] Generating reflection.pb.cc, reflection.pb.hh
Scanning dependencies of target reflection
[ 45%] Building CXX object third_party/gRPC_utils/CMakeFiles/reflection.dir/proto_reflection_descriptor_database.cc.o
[ 50%] Building CXX object third_party/gRPC_utils/CMakeFiles/reflection.dir/cli_call.cc.o
[ 54%] Linking CXX static library libreflection.a
[ 54%] Built target reflection
Scanning dependencies of target cli
[ 59%] Building CXX object src/libCli/CMakeFiles/cli.dir/MessageParsing.cpp.o
[ 63%] Building CXX object src/libCli/CMakeFiles/cli.dir/OutputFormatting.cpp.o
[ 68%] Building CXX object src/libCli/CMakeFiles/cli.dir/GrammarConstruction.cpp.o
[ 72%] Building CXX object src/libCli/CMakeFiles/cli.dir/Completion.cpp.o
[ 77%] Building CXX object src/libCli/CMakeFiles/cli.dir/Call.cpp.o
[ 81%] Building CXX object src/libCli/CMakeFiles/cli.dir/cliUtils.cpp.o
[ 86%] Linking CXX static library libcli.a
[ 86%] Built target cli
Scanning dependencies of target versionDefine
[ 86%] Built target versionDefine
Scanning dependencies of target compileCommands
cp: '/home/ekarlso/software/gWhisper/compile_commands.json' and '/home/ekarlso/software/gWhisper/compile_commands.json' are the same file
make[2]: *** [src/CMakeFiles/compileCommands.dir/build.make:57: src/CMakeFiles/compileCommands] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: src/CMakeFiles/compileCommands.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by ericboehmler** [comment]
Hi.
Our intention is to keep the src and build tree separated. The script build.sh is creating the subdir "build" for that reason. By calling 'cmake .' you are setting the build directory to the src directory and a cmake rule fails. A patch is in the pipe to make this more robust. Please try using build.sh meanwhile.
