### ISSUE TITLE
the last character of string in the repeated field is missing

### ISSUE THREAD

**Issue by taojunli** [IBM/gWhisper#86]
**Describe the bug**
`./gwhisper 0.0.0.0:50021 examples.ComplexTypeRpcs echoNumberAndStrings number_and_strings=::str=text number=0::                                                                                          `

2020-07-02 00:15:39: Received message:
| number_and_strings[1/1] = {NumberAndString}
| | number = 0 (0x00000000)
| | str... = "tex"

**To Reproduce**
This bug was introduced in commit 9bc206e7d32f6fd62a88c5681a421cd88318063b: **Implement escaping in strings (escape character is ':')**

**Expected behavior**
2020-07-02 00:15:39: Received message:
| number_and_strings[1/1] = {NumberAndString}
| | number = 0 (0x00000000)
| | str... = "text"

**Comment by rainerschoe** [comment]
solved in master branch. Thanks @taojunli 
I think we should do a minor version release, since this bug is quite significant.

**Comment by taojunli** [comment]
> solved in master branch. Thanks @taojunli
> I think we should do a minor version release, since this bug is quite significant.

yes i need a new minor version  :)
